version: "3.9"

services:
  evolution-api:
    image: atendai/evolution-api:2.3.1
    container_name: evolution-api
    ports:
      - "8080:8080"
    env_file:
      - .env.evolution
    volumes:
      - ./evolution-api:/evolution-api-data
    restart: unless-stopped
